"""Defines Data Transfer Objects (DTOs) for the Task module.

This module uses Pydantic's BaseModel to create classes that define the
shape and validation rules for data moving in and out of the application's
API endpoints related to tasks. These DTOs serve as a clear and enforceable
contract for the API.
"""
from pydantic import BaseModel, Field
from typing import Optional

from backend.task.enums import TaskStatus


class TaskCreate(BaseModel):
    """DTO for creating a new task.

    This model is used to validate the request body when a client sends a
    request to create a new task. It ensures that the required fields are
    present and meet the specified constraints.

    Attributes:
        title (str): The title of the task. Must be between 1 and 255
            characters.
        description (Optional[str]): An optional, detailed description of the
            task. Defaults to None.
    """
    title: str = Field(..., min_length=1, max_length=255, description="The title of the task.")
    description: Optional[str] = Field(None, description="The optional description of the task.")


class TaskUpdate(BaseModel):
    """DTO for updating an existing task. All fields are optional.

    This model is used to validate the request body for updating a task.
    Since all fields are optional, a client can send only the fields they
    wish to change, allowing for partial updates (PATCH-like behavior
    with a PUT or PATCH method).

    Attributes:
        title (Optional[str]): The new title for the task. If provided, must
            be between 1 and 255 characters.
        description (Optional[str]): The new description for the task.
        status (Optional[TaskStatus]): The new status for the task, which must
            be a valid member of the `TaskStatus` enum.
    """
    title: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = None
    status: Optional[TaskStatus] = None


class TaskDTO(BaseModel):
    """DTO for representing a task in API responses.

    This model defines the structure of a task object as it is sent back to
    the client. It includes all the relevant fields of a task, including
    those generated by the database like `id` and `owner_id`.

    Attributes:
        id (int): The unique, database-generated identifier for the task.
        title (str): The title of the task.
        description (Optional[str]): The detailed description of the task.
        status (TaskStatus): The current status of the task, represented by the
            `TaskStatus` enum.
        owner_id (int): The ID of the user who owns the task.
    """
    id: int
    title: str = Field(..., min_length=1, max_length=255, description="The title of the task.")
    description: Optional[str] = Field(None, description="The optional description of the task.")
    status: TaskStatus
    owner_id: int

    class Config:
        """Pydantic configuration to allow ORM model mapping.

        The `from_attributes = True` setting enables the Pydantic model to be
        created from an arbitrary class instance (like a SQLAlchemy ORM model)
        by reading its attributes, not just from dictionaries.
        """
        from_attributes = True